const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path'),os=require('os');
const {createCanvas,loadImage}=require('@napi-rs/canvas');
const root=path.resolve(__dirname,'../dist')+'/';const {pathToFileURL}=require('url');
const output=process.env.NOCT_TEST_OUTPUT||path.join(os.tmpdir(),'noct-test-output');fs.mkdirSync(output,{recursive:true});
const objects=new Map();let serial=0;
const bucket={async get(k){const v=objects.get(k);return v?{body:v.text,httpEtag:v.etag,text:async()=>v.text}:null},async put(k,text,opts){const old=objects.get(k),h=opts.onlyIf;if(h.get('If-Match')&&old?.etag!==h.get('If-Match')||h.get('If-None-Match')==='*'&&old)return null;const etag='"'+(++serial)+'"';objects.set(k,{text,etag});return {httpEtag:etag}}};
(async()=>{
 const {homeAPI}=await import(pathToFileURL(path.resolve(__dirname,'../server.mjs')));
 const api=(body,user='test-player',headers={},method='PUT')=>homeAPI(new Request('https://noct.example/api/home',{method,headers:{...(user?{'oai-authenticated-user-id':user}:{}),'Content-Type':'application/json',...headers},...(method==='PUT'?{body:JSON.stringify(body)}:{})}),{BUCKET:bucket});
 assert.equal((await api(null,null,{},'GET')).status,401);
 const images=[],loads=[],events={};
 for(const file of ['forest-cute.png','noct-walk-4dir.png','noct-stand.png','home-map.png',...['radish','bell'].flatMap(c=>[0,1,2,3].map(s=>`crop-${c}-${s}.png`)),...['plot','plot-upgraded','wood','stone'].map(n=>`home-${n}.png`),...['moonshadow','wetland','snowfield','ashcanyon'].map(id=>`maps/${id}.webp`)])images.push(await loadImage(root+file));
 function Image(){const img=images.shift();assert(img,'unexpected image');Object.defineProperty(img,'src',{set(){}});Object.defineProperty(img,'complete',{get:()=>true});Object.defineProperty(img,'naturalWidth',{get:()=>img.width});Object.defineProperty(img,'onload',{set(fn){loads.push(Promise.resolve().then(fn))}});img.decode=()=>Promise.resolve();return img}
 const els={},canvas=createCanvas(640,400);canvas.addEventListener=()=>{};canvas.focus=()=>{};
 function el(s){return els[s]??={style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},focus(){},innerHTML:'',textContent:''}}
 const sandbox={console,Math,Set,Image,Promise,document:{querySelector:s=>s==='#game'?canvas:el(s),querySelectorAll:sel=>{const attr=sel.slice(1,-1),html=el('#panel').innerHTML;return [...html.matchAll(new RegExp(attr+'="([^"]+)"','g'))].map(m=>{const e=el(sel+m[1]);e.dataset[attr.replace('data-','')]=m[1];return e})},createElement:()=>createCanvas(1,1),addEventListener(){}},window:{addEventListener(k,fn){(events[k]??=[]).push(fn)}},fetch:async(url,o={})=>api(o.body?JSON.parse(o.body):null,'test-player',o.headers,o.method||'GET'),requestAnimationFrame(){}};
 vm.createContext(sandbox);vm.runInContext(fs.readFileSync(root+'game.js','utf8'),sandbox);vm.runInContext(fs.readFileSync(root+'home.js','utf8'),sandbox);vm.runInContext(fs.readFileSync(root+'exploration.js','utf8'),sandbox);await Promise.all(loads);await new Promise(r=>setTimeout(r,30));
 const run=s=>vm.runInContext(s,sandbox);
 for(const id of ['moonshadow','wetland','snowfield','ashcanyon'])await run(`loadExplorationMap('${id}')`);
 run(`if(!homeReady||state.zone!=='home'||mode!=='play')throw Error('home boot');if(blockedHome(state.p.x,state.p.y))throw Error('spawn blocked');`);
 run(`for(const [key,direction,facing]of [['w',1,1],['s',0,1],['a',2,-1],['d',2,1]]){enterHome();state.p.x=320;state.p.y=140;keys.add(key);for(let i=0;i<8;i++)tickHome(.02);if(state.p.direction!==direction||(direction===2&&state.p.facing!==facing))throw Error('home walking '+key);keys.clear();for(let i=0;i<30;i++)tickHome(.02);if(state.p.motion!=='idle'||state.p.direction!==0)throw Error('home idle '+key);}enterHome();`);
 run(`openPlot(0);document.querySelectorAll('[data-crop]')[0].onclick();if(home.plots[0]?.type!=='radish')throw Error('plant radish');openPlot(1);document.querySelectorAll('[data-crop]')[1].onclick();if(home.plots[1]?.type!=='bell')throw Error('plant bell');drawHome();`);
 fs.writeFileSync(path.join(output,'home-playable.png'),canvas.toBuffer('image/png'));
 run(`enterHome();pause();if(!$('#panel').innerHTML.includes('下一次出发')||!$('#panel').innerHTML.includes('最大生命'))throw Error('home stats panel');pause();start();state.damage=3;state.rate=.4;state.p.speed=87.36;state.magnet=52;state.flames=2;state.builds={damage:2,haste:1,speed:1,magnet:1,vitality:0,flames:2};pause();const stats=$('#panel').innerHTML;if(!stats.includes('当前属性')||!stats.includes('星光伤害')||!stats.includes('施放频率')||!stats.includes('移动速度')||!stats.includes('拾取范围')||!stats.includes('环绕鬼火')||!stats.includes('闪耀吊坠 ×2')||!stats.includes('2.5 / 秒')||!stats.includes('112%'))throw Error('forest stats panel');pause();`);
 run(`start();state.time=29;state.loot={wood:3,stone:2,star:1};end(false,true);if(home.plots[0].growth!==0)throw Error('early growth');const n=home.wood;end(true);if(home.wood!==n)throw Error('duplicate settlement');enterHome();start();state.time=35;end(false,true);enterHome();start();state.time=180;state.loot={wood:10,stone:6,star:5};end(true);enterHome();if(home.plots[0].growth!==2||home.plots[1].growth!==2)throw Error('growth');openPlot(0);document.querySelector('#home-action-0').onclick();if(home.radish!==3||home.plots[0]!==null)throw Error('harvest');openHouse();document.querySelector('#home-action-0').onclick();if(home.house!==1)throw Error('house');openBench();document.querySelector('#home-action-1').onclick();if(!home.blessing||home.radish!==1)throw Error('soup');start();if(state.p.max!==7||home.blessing)throw Error('home bonuses');state.time=40;end(false,true);enterHome();openPlot(1);document.querySelector('#home-action-0').onclick();if(home.bell!==2)throw Error('flower harvest');home.wood=100;home.stone=100;home.star=100;openWorkshop();document.querySelectorAll('[data-build]')[0].onclick();if(home.plots.length!==4)throw Error('expansion');openWorkshop();document.querySelectorAll('[data-build]')[0].onclick();if(home.workshop!==1)throw Error('workshop');openWorkshop();document.querySelectorAll('[data-build]')[0].onclick();if(home.garden!==1)throw Error('garden');`);
 // A walkable pixel-grid path exists to every interaction after expansion.
 run(`const queue=[{x:301,y:149}],seen=new Set(),targets=nearbyObjects(),found=new Set();while(queue.length){const a=queue.shift(),key=a.x+','+a.y;if(seen.has(key))continue;seen.add(key);for(const t of targets)if(dist({x:a.x,y:a.y+12},t)<67)found.add(t.id);for(const [dx,dy]of [[5,0],[-5,0],[0,5],[0,-5]]){const n={x:a.x+dx,y:a.y+dy};if(!blockedHome(n.x,n.y)&&!seen.has(n.x+','+n.y))queue.push(n)}}if(found.size!==targets.length)throw Error('unreachable '+targets.filter(t=>!found.has(t.id)).map(t=>t.id));`);
 run(`home.plots=[{type:'radish',growth:2},{type:'bell',growth:3},{type:'radish',growth:1},{type:'bell',growth:0}];persistHome();drawHome();`);
 fs.writeFileSync(path.join(output,'home-grown.png'),canvas.toBuffer('image/png'));
 await new Promise(r=>setTimeout(r,30));
 const saved=await (await api(null,'test-player',{},'GET')).json();assert.equal(saved.house,1);assert.equal(saved.plots.length,4);
 assert.equal((await api(null,'other-player',{},'GET')).status,200);assert.equal(await (await api(null,'other-player',{},'GET')).json(),null);
 assert.equal((await api(saved,'test-player',{'If-Match':'"outdated"'})).status,200); // identical retry is idempotent
 assert.equal((await api({...saved,wood:1},'test-player',{'If-Match':'"outdated"'})).status,409);
 assert.equal((await api({...saved,plots:[{type:'malicious',growth:0},null]},'test-player',{'If-None-Match':'*'})).status,400);
 assert.equal((await api(saved,'test-player',{'Origin':'https://elsewhere.example','If-None-Match':'*'})).status,403);
 run(`home.wood=0;awaitValue=loadHome()`);await sandbox.awaitValue;assert.equal(run('home.wood'),saved.wood);
 // All four maps: reachable drops, safe spawning, bounded camera, solid terrain,
 // deterministic frozen ambient pass and all settlement branches.
 for(const id of ['moonshadow','wetland','snowfield','ashcanyon']){
  run(`selectedMap='${id}';start();if(state.mapId!=='${id}'||state.zone!=='forest')throw Error('map start');if(explorationBlocked(state.p.x,state.p.y+12))throw Error('blocked player');for(const n of state.nodes)if(explorationBlocked(n.x,n.y,10)||state.flow[cellIndex(n.x,n.y)]<0)throw Error('unreachable drop');for(let i=0;i<100;i++){const p=pickExplorationSpawn();if(p&&(explorationBlocked(p.x,p.y,15)||dist(p,state.p)<180))throw Error('bad spawn')}for(const s of mapSpecs[state.mapId].solids){if(!s.points&&!blockedForMap(state.mapId,s.x*MAP_SCALE,s.y*MAP_SCALE,0))throw Error('solid not collidable')}for(const x of [20,1024,2028])for(const y of [20,640,1260]){const c=cameraFor({x,y});if(c.x<0||c.y<0||c.x+W>WORLD_W||c.y+H>WORLD_H)throw Error('camera bounds')}state.ambientTime=4;draw();`);
  fs.writeFileSync(path.join(output,id+'-playable.png'),canvas.toBuffer('image/png'));
  run(`state.p.x=1760;state.p.y=250;state.ambientTime=3;draw();`);const still=canvas.toBuffer('image/png');run('draw()');assert(still.equals(canvas.toBuffer('image/png')),'ambient moves while paused');run('state.ambientTime=5;draw()');assert(!still.equals(canvas.toBuffer('image/png')),'no ambient change');
  run(`ambientEnabled=false;draw()`);const disabled=canvas.toBuffer('image/png');run('state.ambientTime=7;draw()');assert(disabled.equals(canvas.toBuffer('image/png')),'disabled ambient moves');run('{ambientEnabled=true;state.p.x=1024;state.p.y=656;state.p.hp=100;state.p.max=100;state.time=179.99;tick(.02);if(mode!=="extraction")throw Error("3 minute choice");const before=state.time;frame(100);if(state.time!==before)throw Error("choice not paused");document.querySelector("#explore-more").onclick();state.time=239.99;tick(.02);if(mode!=="end"||!state.settled)throw Error("4 minute finish");enterHome();}');
 }
 run(`selectedMap='moonshadow';start();state.time=180;tickExploration(0);const oldWood=home.wood;document.querySelector('#extract-now').onclick();if(!state.settled||home.wood!==oldWood+4)throw Error('180s reward');const once=home.wood;end(true);if(home.wood!==once)throw Error('map double reward');enterHome();openGate();if(document.querySelectorAll('[data-map]').length!==4)throw Error('map selection');closeHomeDialog();`);
 // Render peripheral landmarks where subtle ambient patches are actually visible.
 const review=createCanvas(1280,800),reviewCtx=review.getContext('2d');
 for(const [i,id]of ['moonshadow','wetland','snowfield','ashcanyon'].entries()){
  run(`selectedMap='${id}';start();state.p.hp=100;state.p.max=100;state.p.x=1660;state.p.y=330;updateExplorationFlow(0,true);for(let j=0;j<1500;j++){if(mode==='upgrade'){mode='play';state.xp=0;}tick(.02);}if(state.enemies.length===0&&state.kills===0)throw Error('combat spawn missing');for(const e of state.enemies)if(explorationBlocked(e.x,e.y,e.r-.1))throw Error('enemy inside solid');state.ambientTime=12;draw();`);
  reviewCtx.drawImage(canvas,(i%2)*640,Math.floor(i/2)*400);
 }
 fs.writeFileSync(path.join(output,'noct-ambient-review.png'),review.toBuffer('image/png'));
 console.log('PASS home boot, reachable interactions, planting, 30s growth threshold, harvest, one-time settlement, soup/building bonuses, all upgrades, account save/reload, isolation, stale-save and invalid-write rejection.');
 console.log('PASS four map selections, world bounds, colliders, reachable resources, offscreen spawning, ambient freeze/toggle, three-minute extraction and four-minute one-time settlement.');
})().catch(e=>{console.error(e);process.exit(1)});
